services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: bank_db
    ports:
      - "5432:5432"
    networks:
        - app-network
  
  go-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
